version: "3"

services:
  express:
    container_name: "express"
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - APP_ENV=${APP_ENV}
    volumes:
      - ${APP_FOLDER}:/usr/src/app
    ports:
      - "8000:8000"
    networks:
      - dev

  mongo:
    image: mongo:latest
    container_name: db
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - db-data:/data/db
    ports:
      - 27018:27017
    logging:
      driver: none
    restart: unless-stopped
    networks:
      - dev

networks:
  dev:
volumes:
  db-data:
